/**
 * NanoBanana Pro Image Generation Service
 *
 * Uses Google Gemini API for AI image generation.
 * This service provides text-to-image capabilities using Gemini's image generation model.
 */

const crypto = require('crypto');

// Encryption for API keys (same as other services)
const ENCRYPTION_KEY = process.env.ENCRYPTION_KEY || '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef';
const ALGORITHM = 'aes-256-gcm';

function decrypt(encryptedData) {
  const parts = encryptedData.split(':');
  const iv = Buffer.from(parts[0], 'hex');
  const authTag = Buffer.from(parts[1], 'hex');
  const encrypted = parts[2];
  const key = Buffer.from(ENCRYPTION_KEY, 'hex');
  const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
  decipher.setAuthTag(authTag);
  let decrypted = decipher.update(encrypted, 'hex', 'utf8');
  decrypted += decipher.final('utf8');
  return decrypted;
}

class NanoBananaService {
  constructor() {
    this.defaultApiKey = process.env.NANOBANANA_API_KEY;
    this.baseUrl = 'https://generativelanguage.googleapis.com/v1beta';
    this.model = 'models/gemini-3-pro-image-preview';
  }

  /**
   * Get user's API key from database
   */
  async getUserApiKey(prisma, userId) {
    if (!prisma || !userId) {
      return this.defaultApiKey;
    }

    try {
      const apiKeyRecord = await prisma.apiKey.findFirst({
        where: { userId, provider: 'nanobanana' }
      });

      if (apiKeyRecord) {
        return decrypt(apiKeyRecord.encryptedKey);
      }
    } catch (error) {
      console.error('Error fetching NanoBanana API key:', error);
    }

    return this.defaultApiKey;
  }

  /**
   * Generate image from text prompt using Google Gemini
   * @param {string} prompt - Text description of the image
   * @param {object} options - Generation options
   */
  async generateImage(prompt, options = {}) {
    const {
      aspectRatio = '16:9',
      style = 'cinematic',
      apiKey = null
    } = options;

    const key = apiKey || this.defaultApiKey;
    if (!key) {
      throw new Error('Google API key not configured. Please add your API key in Settings.');
    }

    // Enhance prompt with style
    const enhancedPrompt = `${style} style image: ${prompt}. High quality, detailed, professional.`;

    const url = `${this.baseUrl}/${this.model}:generateContent?key=${key}`;

    const body = {
      contents: [{
        parts: [{
          text: `Generate an image: ${enhancedPrompt}`
        }]
      }],
      generationConfig: {
        responseModalities: ["TEXT", "IMAGE"]
      }
    };

    console.log('[Gemini Image] Calling API:', { model: this.model, promptLength: enhancedPrompt.length });

    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify(body)
    });

    const data = await response.json();

    if (!response.ok) {
      console.error('[Gemini Image] API Error:', data);
      throw new Error(data.error?.message || `Gemini API error: ${response.status}`);
    }

    console.log('[Gemini Image] Response received:', {
      hasCandidates: !!data.candidates,
      candidatesCount: data.candidates?.length
    });

    // Extract image from response
    const candidates = data.candidates || [];
    if (candidates.length === 0) {
      throw new Error('No image generated by Gemini');
    }

    const parts = candidates[0]?.content?.parts || [];
    const imagePart = parts.find(p => p.inlineData?.mimeType?.startsWith('image/'));

    if (imagePart) {
      // Return base64 image data directly
      const base64Data = imagePart.inlineData.data;
      const mimeType = imagePart.inlineData.mimeType;
      const ext = mimeType.split('/')[1] || 'png';

      return {
        success: true,
        data: {
          image_url: `data:${mimeType};base64,${base64Data}`,
          image_base64: base64Data,
          format: ext,
          status: 'completed'
        }
      };
    }

    // Check if there's text explaining why no image
    const textPart = parts.find(p => p.text);
    if (textPart) {
      throw new Error(`Gemini response: ${textPart.text}`);
    }

    throw new Error('No image in Gemini response');
  }

  /**
   * Check image generation task status (not needed for Gemini - synchronous)
   */
  async getTaskStatus(taskId, apiKey = null) {
    // Gemini generates images synchronously, no task polling needed
    return {
      success: true,
      data: {
        task_id: taskId,
        status: 'completed'
      }
    };
  }

  /**
   * Get image URL from completed task
   * @param {string} taskId - The task ID to check
   */
  async getImageUrl(taskId) {
    const status = await this.getTaskStatus(taskId);

    if (status.data.status === 'completed' && status.data.images.length > 0) {
      return status.data.images[0].url || status.data.images[0];
    }

    return null;
  }

  /**
   * Test API connection
   */
  async testConnection() {
    try {
      if (!this.apiKey) {
        return {
          success: false,
          message: 'Missing NanoBanana API key',
          hasApiKey: false
        };
      }

      // Try to get account info or make a simple request
      // Adjust endpoint based on actual NanoBanana API
      return {
        success: true,
        message: 'NanoBanana API key configured',
        hasApiKey: true
      };
    } catch (error) {
      return {
        success: false,
        message: error.message,
        hasApiKey: !!this.apiKey
      };
    }
  }
}

module.exports = new NanoBananaService();
